### ISSUE TITLE
Update to support entt v3.10.3 and sol v3.3.0

### ISSUE THREAD

**Issue by reworks-org** [skaarj1989/entt-meets-sol2#1]
Would really be appreciated.

A couple of issues I partially solved myself when attempting this myself:

- emplace_component binding for registry - had to make sure the instance.as() was wrapped in std::move() to avoid copying component.
- Had to explicitly construct base script event, trigger() could no longer infer the type.
- Meta helper seemed fine.
- replaced sol::meta_function::construct with sol::constructors<>() - this is better than defining the factory.

I didnt't use the scheduler, but it appears that dispatcher has the most issues.

**Comment by DomRe** [comment]
I used this as a reference, should be helpful.

https://github.com/ThePhD/sol2/issues/776

I think the dispatcher changes are mostly on entt's end, however. Sol3 is pretty good with backwards compatibility.

**Comment by reworks-org** [comment]
I've done a basic port if it helps.

https://github.com/DomRe/galaxy/tree/master/lib/entt/include/entt/addons/sol
